stages:
- test
- docker_build
test:
  image: "python:3"
  stage: test
  script:
  - make deps
  - make test
docker:
  image: docker:stable
  services:
    - docker:dind
  stage: docker_build
  script:
  - apk add --update make
  - make docker_build
  - docker login registry.gitlab.com
  - docker build -t registry.gitlab.com/mylosz93/se_hello_printer_app .
  - docker push registry.gitlab.com/mylosz93/se_hello_printer_app
