language: python
services:
  - docker
python:
  - "3.8"
install:
  - make deps
scripts:
  - make test
  - make lint
  - make docker_build
  - make docker_push
  - make test_xunit
deploy:
    provider: heroku
    app: enigmatic-bastion-04190
    api_key: ${HEROKU_API_KEY}
